### ISSUE TITLE
How to use Evergine Nightly repository?

### ISSUE THREAD

**Issue by adamthole** [EvergineTeam/Feedback#112]
In Evergine Studio I can install Evergine Nightly builds, and I can upgrade my project to use them.  However after upgrading my project to use them it can't be built anymore as the nightly packages are not on the nuget.org package source.

Is there a different package source we can add to get access to the nightly builds?  Is there some other way of using the Nightly builds that I am missing?

Worth noting, I'm interested in trying a Nightly build as I'm wanting to get the MacOS version of my Evergine project working.  I can't seem to get a response to this issue: https://github.com/EvergineTeam/Feedback/issues/68 but I thought perhaps I would try to get a little further using a Nightly build.

Any information you can share on the Nightly build (or even better, an update on MacOS support) would be greatly appreciated.

Thanks!

**Comment by emepetres** [comment]
@adamthole thank you for your report. If you upgrade a preview/stable project to nightly version, you need to add a nuget.config file with the following information in the same folder as the solution:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
    <add key="Evergine Nightly" value="https://pkgs.dev.azure.com/plainconcepts/Evergine.Nightly/_packaging/Evergine.NightlyBuilds/nuget/v3/index.json" />
  </packageSources>
</configuration>
```

The reason is that nightly builds are not in nuget.org. If you create a nightly project directly, the nuget.config file will be created automatically.

Anyway this is something we can improve and will do shortly. If you need a quick resolution or more detailed support, please check out our [priority support](https://evergine.com/priority-support/).

**Comment by adamthole** [comment]
@emepetres  That worked perfectly, I was able to upgrade to the latest nightly build without an issue.  Thank you for the help, and thank you for making the nightly builds available!

**Comment by emepetres** [comment]
@adamthole glad it helped! BTW this has been fixed in tonight nightly, so no need to edit manually nuget.config in the future.
