### ISSUE TITLE
Problem with NuGet restore

### ISSUE THREAD

**Issue by zejtin** [EvergineTeam/Feedback#15]
I've installed WaveEngine version 2.5.0.39 and created new project but i get the following error:
![image](https://user-images.githubusercontent.com/18098346/79945535-39403680-846e-11ea-9bdf-96d3b8e6c7cb.png)
I've opened the project in visual studio and restored packages but the problem persists, in visual studio it even builds. 

I have also tried some example projects and I get the same mistake

**Comment by drigon01** [comment]
hi @zejtin I run into the same problem, and this seems to be a Nuget and VS realated issue as far as i understand based on this thread : https://developercommunity.visualstudio.com/content/problem/953357/nuget-restore-step-is-failing-with-new-msbuild-ver.html
What version of VS were you using? (in my case its VS 2019 community edition)

**Comment by zejtin** [comment]
hi @drigon01 Same as you - VS2019 community

**Comment by emepetres** [comment]
@zejtin  thank you for your report and sorry for the late response. I'm closing the issue due to the fact that now we are only giving support for Evergine versions. Please, if you need a solution feel free to reopen it. Anyway for a quick resolution, please check our [priority support](https://evergine.com/priority-support/).
