### ISSUE TITLE
Basic docu for code-based entrance

### ISSUE THREAD

**Issue by FrankBusch68** [EvergineTeam/Feedback#50]
Hi,
I want to use WaveEngine without UI-Editor, but just from Code-Side. So I am looking for a point to start at to get into this.

I found the example at https://github.com/WaveEngine/LowLevelAPIDemo. This might be a good idea, but what I need to start is a lot more basic... 

Something like: Everything is black. We add a light. Then put s single unrepeated jpg on the ground (including steps to transfer it into a usable format). Now add a camera at some point, looking to another point with a viewangle of... Move the camera (position, point-of-view, viewangle) best driven by time and(!) cursor-keys.
Next step: Add a sphere to this scene and move it around.
Next step: Add two or three basic things like a cube and a cylinder to the scene.
Next step: modify the objects (color, size, form, transparency, glance, maybe even texture).
Next step: Maybe add some sky to make the scene look better
Next steps could be (but are maybe a later version) §D-objects, more texture and some physics...

After these simple first steps I would be able to really start reading the API and/or documentation because I got the basic concepts and known what all the text really tells me.

Is it possible to get somthing like this?

<edit>
Sorry, forgot to say thanks in advance

Frank
</edit>

**Comment by davilovick** [comment]
Hi Frank,

One thing that we need to work in the future is to develop better documentation of Wave development.  Meanwhile, sorry for the inconveniences.

In WaveEngine, you can develop your application whitout using the Wave Editor. However is more easy to manage your assets, profiles, etc... 

In that case, I reconmend you to create a Wave Project from Wave Editor, and then, open the solution in Visual Studio. 
By default,  when you run the application.. it launchs a scene defined in a Scene asset in Wave Editor (MyScebe.wescene file). But you could avoid that step:
- Open the file MyApplication.cs in your code Editor.
- Remove the followng line: **var scene = assetsService.Load<MyScene>(WaveContent.Scenes.MyScene_wescene);**
- Replace with the following line: **var scene = new MyScene();**
- In that case you are creating new scene from code (a inherited scene class called MyScene, that allows you to control the creation of this scene)

If you have completed the previous steps, you will see a blank screen, because the scene cannot contains any entity :)

In the following pastebin: https://pastebin.com/rFuLtCe7, you can find a replacement of the MyScene.cs file, which I've included several entities and comments to help in your purposes :)

I hope that this code helps you to undestand how Wave Engine works

Best regards,
David Ávila

**Comment by FrankBusch68** [comment]
Thanks so far, I will give it a try
Frank

**Comment by FrankBusch68** [comment]
That worked so far.

Now I have the next problems. I want to add a sphere rolling around. Adding a sphere with addComponent(new sphere(1,1)) brings a error because a sphere is no component? WaveEngine.COMPONENTS.Primitives is no component?

Then I tried to move the camera. Finding the Transform3D in the Cam and changing position does not change anything. Dropping the cam an creating a new one works in step-by-step debug, but crashes when removing the breakpoint. A spinner (just a try) has no effect. I have no clue how animations are handled and whether they would do anything in here...

I think this Framework has great capabilities, but I don't get the point to really get it running.

When looking into the API this is a reference, OK. But it does not explain anything.

**Comment by FrankBusch68** [comment]
By the way... I use WaveEngine 3.1 Preview 2

**Comment by davilovick** [comment]
Hi Frank, 
In WaveEngine, we have components that generate meshes (for example, the PlaneMesh component that I used in the pastebin).
- PlaneMesh
- CubeMesh
- SphereMesh
- TeapotMesh
- TorusMesh
The Sphere class is a internal structure to define the shape, not the component itself :)

If you want to move the Camera entity, is correct to get the Transform3D component and change the position:
`cameraEntity.FindComponent<Transform3D>().LocalPosition = newPosition`
If that is not working, try to check if the chosen entity is correct camera Entity.

PD: You are correct that we need to put a lot of effort to improve the documentation, and We hope to go better in that aspect in the future :)
